---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 758062138275397632-dDAEcbfcKmTIvXY36cRnCD2mBYAgpsn
:access_token_secret: FP2VkbvGKvb05BBaWhMUI0gmbqLtXwonIRAn2bu2lEUep
